### ISSUE TITLE
Mixed content warning

### ISSUE THREAD

**Issue by molnarm** [molnarm/igemutato#34]
HTTPS-es oldalakban a betöltés mindig sikertelen. A szkript maga betöltődhet https-en, de az AJAX kérésekhez nincs tanúsítvány a szentiras.hu-n, erre ki kell találni valamit...

**Comment by borazslo** [comment]
Kéne egy saját certificate a szentiras.hu-hoz? Mondjuk innen: https://letsencrypt.org/ ?

**Comment by molnarm** [comment]
Hosszútávon mindenképpen, ez lassan mindenhol szinte kötelező lesz. Egyelőre csak annyi a probléma, hogy HTTPS-es oldalakon (amiből egyre több van) nem működik a bővítmény, mert nem biztonságos kapcsolaton tölt be külső adatokat.

**Comment by molnarm** [comment]
Ha a szentiras.hu-n lesz HTTPS, akkor ez már automatikusan jól fog működni.
